name: basit-workflowum

on: 
  push:
    branches:
      - step-output
    paths:
      - '.github/workflows/status-check-functions.yml'

jobs:
  ekrana-bas:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Uygulamami Calistir
        id: uygulamami-calistir
        run: |
          cd hodo
          echo "degisiklik_var=$(git status -s | wc -l | xargs)" >> $GITHUB_OUTPUT
      - name: Degisiklik Yoksa Calisan Adim
        if: ${{ success() }}
        run: |
          echo "Degisiklik yok"
      - name: Degisiklik Varsa Calisan Adim
        if: ${{ failure() }}
        run: |
            echo "Degisiklik var"
        
